application: link-it-portal
version: oct2018v2
runtime: python27
api_version: 1
threadsafe: true

handlers:
#static dir handlers
- url: /super/assets
  static_dir: src/super/assets  
  
- url: /js
  static_dir: src/endclient/js 
  
- url: /css
  static_dir: src/endclient/css  

- url: /img
  static_dir: src/endclient/img  

- url: /images
  static_dir: src/endclient/images  

- url: /fonts
  static_dir: src/endclient/fonts  

- url: /lang
  static_dir: src/endclient/lang  

- url: /html
  static_dir: src/endclient/html  

- url: /php
  static_dir: src/endclient/php  
  
- url: /light
  static_dir: src/endclient/light  
  
- url: /test
  static_dir: src/endclient/test  
  
- url: /productdesigner
  static_dir: src/endclient/productdesigner
    
- url: /photobook
  static_dir: src/endclient/photobook  
  
- url: /wp-content    
  static_dir: src/wp-content

#URL handler  
- url: /taskqueue/.*
  script: src.Actions.taskqueue.app
  
- url: /superadmin
  script: src.main.app 
  login: required
  
- url: /Seller
  script: src.main.app 
  login: required
    
- url: /.*
  script: src.main.app 

 
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto 
  version: latest
- name: endpoints
  version: 1.0
